site_name: Orthweb - Orthanc Solution on AWS
repo_name: digihunch/orthweb
repo_url: https://github.com/digihunch/orthweb
strict: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append: ["../LICENSE"]
      base_path: ["docs"]

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - Introduction: 'introduction/index.md'
  - Architecture:
    - 'Infrastructure': 'design/infrastructure.md' 
    - 'Configuration Management': 'design/configmgmt.md'
    - 'Ingress Traffic': 'design/ingress.md'
    - 'Device Connectivity': 'design/deviceconnectivity.md'
  - Deployment:
    - 'Preparation': 'deployment/preparation.md'
    - 'Infrastructure': 'deployment/infrastructure.md'
    - 'Configuration': 'deployment/configuration.md'
  - Validation: 
    - 'Basic Validation': 'validation/basic.md'
    - 'Advanced Validation': 'validation/advanced.md'
    - 'Additional Validation': 'validation/additional.md'
  - Brian's Notes: 
    - 'Deploy': 'brians-notes/deploy.md'
    - 'User Management': 'brians-notes/user-management.md'
    - 'Troubleshooting': 'brians-notes/troubleshooting.md'
    - 'TODO': 'brians-notes/todo.md'

  - Support: 'support/index.md'

plugins:
  - search
  - include-markdown
